### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by wtfbbqhax** [TheDushan/OWEngine#1]
# Hello

Sorry to spoil your GH#Issues with off topic; I basically wanted to reach out and see if I could pick your brain about one or more of your previous projects in engine dev. I'm in a position where I _need_ to rearchitect my current engine- I have a few approaches in mind, to my surprise you've actually done previously. If I could bounce some ideas off you, I'd be much appreciated.

Cheers,
~wtfh4x

**Comment by wtfbbqhax** [comment]
@TheDushan Thanks, I'll be in touch 👍

**Comment by TheDushan** [comment]
OK

**Comment by wtfbbqhax** [comment]
Skype invite sent.

Sorry for Slow response, I was consumed with writing a cmake system 😆
